version: '3.5'
services:
  item-intentory:
    image: bmainaliibm/item-aggreagate:1
    expose:
      - 8080
    environment: 
        KAFKA_BROKERS: ${KAFKA_BROKERS}
        KAFKA_USER: ${KAFKA_USER}
        KAFKA_PASSWORD: ${KAFKA_PASSWORD}
        KAFKA_CERT_PATH: ${KAFKA_CERT_PATH}
        KAFKA_CERT_PWD: ${KAFKA_CERT_PWD}
        SECURE_PROTOCOL: ${SECURE_PROTOCOL}
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - item-intentory
    ports:
      - "4000:4000"