version: '3.5'
services:
  item-intentory1:
    image: ibmcase/item-aggregator:0.0.6
    ports:
      - 8080:8080
    environment: 
        KAFKA_BROKERS: ${KAFKA_BROKERS}
        KAFKA_USER: ${KAFKA_USER}
        KAFKA_PASSWORD: ${KAFKA_PASSWORD}
        KAFKA_CERT_PATH: ${KAFKA_CERT_PATH}
        KAFKA_CERT_PWD: ${KAFKA_CERT_PWD}
        SECURE_PROTOCOL: ${SECURE_PROTOCOL}
        QUARKUS_PROFILE: dev
  item-intentory2:
    image: ibmcase/item-aggregator:0.0.6
    ports:
      - 8081:8080
    environment: 
        QUARKUS_PROFILE: dev
        KAFKA_BROKERS: ${KAFKA_BROKERS}
        KAFKA_USER: ${KAFKA_USER}
        KAFKA_PASSWORD: ${KAFKA_PASSWORD}
        KAFKA_CERT_PATH: ${KAFKA_CERT_PATH}
        KAFKA_CERT_PWD: ${KAFKA_CERT_PWD}
        SECURE_PROTOCOL: ${SECURE_PROTOCOL}
