apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-aggregator
  labels:
    app: item-aggregator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: item-aggregator
    spec:
      containers:
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      

