apiVersion: v1
kind: ConfigMap
metadata:
  name: item-aggregator-cm
data:
  APP_VERSION: 0.0.4
  INVENTORY_TOPIC: item.inventory
  ITEM_TOPIC: items
  KAFKA_BOOTSTRAP_SERVERS: dev-kafka-kafka-bootstrap.rt-inventory.svc:9093
  QUARKUS_KAFKA_STREAMS_TOPICS: items,item.inventory
  QUARKUS_KAFKA_HEALTH_ENABLED: "false"
  QUARKUS_KAFKA_STREAMS_HEALTH_ENABLED: "false"
  QUARKUS_KAFKA_CONNECTOR_HEALTH_ENABLED: "false"
  